### ISSUE TITLE
infinite loop in parsenumber()

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/GcodeCNCDemo#11]
float parsenumber(char code,float val) {
  char _ptr=buffer;
  while(ptr && *ptr && ptr<buffer+sofar) {
    if(_ptr==code) {
      return atof(ptr+1);
    }
    ptr=strchr(ptr,' ')+1;
  }
  return val;
} 

if strchr() does not find ' ' it returns null (0) and ptr becomes 1.  while(ptr) would not stop the loop.

while(ptr... should be while(ptr>1...

**Comment by i-make-robots** [comment]
possible fix in 42c0b5d65d51f3352612709255cd09155de4eb32

**Comment by misan** [comment]
just ptr++; worked for me.

You never know if spaces will be in between or not (as they are not mandatory).

**Comment by i-make-robots** [comment]
See makelangelo-firmware for updated version.

**Comment by i-make-robots** [comment]
updated all versions to match makelangelo-firmware, but now github desktop is broken in windows 10.

**Comment by i-make-robots** [comment]
updated all branches to the makelangelo-firmware version.  please confirm it plays nice with the compiler.
