### ISSUE TITLE
in GcodeCNCDemo2Axis.ino line 180 serialBuffer is not declared in this scope? am i missing something

### ISSUE THREAD

**Issue by samiulextreem** [MarginallyClever/GcodeCNCDemo#29]
the error message is 
src\main.cpp: In function 'float parsenumber(char, float)':
src\main.cpp:50:15: error: 'serialBuffer' was not declared in this scope
char *ptr = serialBuffer;
^
pls help me

**Comment by i-make-robots** [comment]
For some reason it's declared at the top of the file as char buffer[MAX_BUF];  looks like I copy pasted some stuff without double checking before commit.
