### ISSUE TITLE
Adafruit Motor Shield v2.

### ISSUE THREAD

**Issue by Lexander24** [MarginallyClever/GcodeCNCDemo#3]
Hello, i want to ask.
If i not use adafruit motor shield, how i can modify your code? thank you

**Comment by i-make-robots** [comment]
Best to discuss it in the forums @ http://marginallyclever.com/forums

Supported added.

On Mon, Jun 29, 2015 at 3:31 AM, Lexander24 notifications@github.com
wrote:

> Hello, i want to ask.
> If i not use adafruit motor shield, how i can modify your code? thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarginallyClever/GcodeCNCDemo/issues/3.

## 

Dan Royer :: Marginally Clever http://www.marginallyclevergroup.com/ ::
Raising Robot Literacy :: +1.604.916.2281
