### ISSUE TITLE
GcodeCNCDemo4AxisCNCShield , not working With tb6600 stepper motor driver

### ISSUE THREAD

**Issue by MohmmedSwan** [MarginallyClever/GcodeCNCDemo#30]
Hello
Thank you very much for this wonderful work
But
The code works in a new way With tb6560 stepper motor driver
Doesn't work with tb6600 stepper motor driver
Can you help?

**Comment by i-make-robots** [comment]
share your wiring diagram.

**Comment by MohmmedSwan** [comment]
Thank you so much
The connections were really wrong.
You made the correct connection.
It works fine for me now
Thank you very much for your help
