### ISSUE TITLE
Error in scrip when making the verification, GcodeCNCDemo2axis

### ISSUE THREAD

**Issue by mboulonne** [MarginallyClever/GcodeCNCDemo#6]
Please let me know why is this error, thanks in advance.

Arduino:1.6.6 (Windows 7), Carte : "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino: In function 'float atan3(float, float)':

GcodeCNCDemo2Axis:119: error: 'float atan3(float, float)' was declared 'extern' and later 'static' [-fpermissive]

 static float atan3(float dy,float dx) {

```
                                 ^
```

GcodeCNCDemo2Axis:41: error: previous declaration of 'float atan3(float, float)' [-fpermissive]

```
   ^
```

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino: In function 'void arc(float, float, float, float, float)':

GcodeCNCDemo2Axis:132: error: 'void arc(float, float, float, float, float)' was declared 'extern' and later 'static' [-fpermissive]

 static void arc(float cx,float cy,float x,float y,float dir) {

```
                                                        ^
```

GcodeCNCDemo2Axis:42: error: previous declaration of 'void arc(float, float, float, float, float)' [-fpermissive]

```
  ^
```

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino: In function 'void where()':

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino:206:16: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   output("X",px);

```
            ^
```

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino:207:16: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   output("Y",py);

```
            ^
```

C:\Users\Michael\Documents\Arduino\GcodeCNCDemo-master\GcodeCNCDemo2Axis\GcodeCNCDemo2Axis.ino:208:16: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   output("F",fr);

```
            ^
```

exit status 1
'float atan3(float, float)' was declared 'extern' and later 'static' [-fpermissive]

  Ce rapport contiendrait plus d'informations si l'option
  "Montrer les informations de sortie pendant la compilation"
  était activée dans Fichier > Préférences.

**Comment by i-make-robots** [comment]
This is a problem with the latest arduino ide, not the code. A workaround is to remove the word "static" at the start of the line. Arduino has been notified and has fixed the bug in their code, it should be better by the next release.

**Comment by mboulonne** [comment]
Thank for the info, Will try that in a few days....

Best regards

Envoyé de mon tél.

Michaël Boulonne 💡
Chef Eclairagiste
mboulonne@gmail.com
M 450.467.4208
C 514.214.2255

**Comment by malipetek** [comment]
Hello, I got the same error, I deleted the static keyword and it worked but only for declaring x y positions not on arcs. So I posted a comment on marginallyclever.com and found this page after googling error message.

**Comment by i-make-robots** [comment]
updated.

On Tue, Feb 2, 2016 at 2:42 AM, malipetek notifications@github.com wrote:

> Hello, I got the same error, I deleted the static keyword and it worked
> but only for declaring x y positions not on arcs. So I posted a comment on
> marginallyclever.com and found this page after googling error message.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarginallyClever/GcodeCNCDemo/issues/6#issuecomment-178503315
> .

## 

Dan Royer :: Marginally Clever http://www.marginallyclevergroup.com/ ::
Raising Robot Literacy :: +1.604.916.2281
