### ISSUE TITLE
How to enter g code to start arduino and control steppers!

### ISSUE THREAD

**Issue by atif241** [MarginallyClever/GcodeCNCDemo#8]
1. I have uploaded the program . Its uploaded succesfully. But now I can not understand how to enter G codes in it. How to write it , how to enter it in arduino serial monitor  to tell the motors to run..
   2.when i upload this program , serial monitor also display a very strange language.
   like this one:
   íæQ·6r.ÌJ‘kÎMð­ð2ázfæYàëNÎëÀbváRJgaNù;îcPíee˜¥9r$Ïä JçB•rU-Ü",ž2"âVÊÅ-€ÊEÐ»
   please help me !!!!

**Comment by i-make-robots** [comment]
This is not an issue with the software.
